## 1. Tensor and Autograd

* tensor: 벡터나 행렬을 일반화한 개념.  
* rank = 차원  

In [14]:
import torch

x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
print(x.shape) # 괄호 없이 사용. shape = size()
print(x.size())
print(x.ndimension()) # 텐서의 rank 확인

torch.Size([3, 3])
torch.Size([3, 3])
2


### 텐서의 랭크와 shape 인위적으로 바꾸기 :  unsqueeze, squeeze, view

#### 1. unsqueeze() : 텐서의 랭크 늘리기 (차원 늘리기)

In [17]:
# 랭크 늘리기
x = torch.unsqueeze(x,0)

In [18]:
print(x)
print(x.shape)
print(x.size())
print(x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])
torch.Size([1, 3, 3])
3


* unsqueeze(x,0)  : 첫번째 자리 (0번째 자리)에 차원값 1 추가하여 랭크 하나 늘렸다.

#### 2. squeeze() : 텐서의 랭크 줄이기 (차원 줄이기)

In [19]:
# 랭크 줄이기
x = torch.squeeze(x)

In [20]:
print(x)
print(x.shape)
print(x.size())
print(x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])
torch.Size([3, 3])
2


#### 3. view() : 원하는 shape으로 직접 변경! (reshape)와 동일.
물론 텐서 원소 수에 맞춰서 view 가능. (예를 들어 원소 수 9인 텐서를 2X4로 변경 불가)

In [22]:
x = x.view(9)
print(x)
print(x.shape)
print(x.size())
print(x.ndimension())

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])
torch.Size([9])
1


### Autograd

In [24]:
w = torch.tensor(1.0, requires_grad = True)

requires_grad = True로 하면 파이토치의 **Autograd가 자동으로 w에 대한 미분 값을 w.grad에 저장**

In [25]:
a = w*3

In [26]:
l = a**2

In [27]:
l.backward()
print('l을 w로 미분한 값은 {}'.format(w.grad))

l을 w로 미분한 값은 18.0


w.grad는 w가 속한 수식을 w로 미분해 반환